/-
This file proves some properties about `forM`, `mapM`, and `foldlM` monad loops when used in a `Circuit`,
typically leveraging a `ConstantLength` assumption on the loop body.

The end result are loop methods `Circuit.{mapFinRange, map, forEach, foldl}` that simplify
under `circuit_norm` in every way we need them to.
-/
module

public import Clean.Circuit.Subcircuit
public import Clean.Utils.Misc
public import Lean.Elab.Tactic

@[expose] public section

open Lean Meta Elab Tactic

variable {n m : ℕ} {F : Type} [FiniteField F] {α β : Type}

lemma Vector.forM_toList (xs : Vector α n) {m : Type → Type} [Monad m] (body : α → m Unit) :
    xs.forM body = forM xs.toList body := by
  rw [Vector.forM_eq_forM, Vector.forM_mk, List.forM_toArray, List.forM_eq_forM]; rfl

lemma Vector.toList_mapM (xs : Vector α n) {m : Type → Type} [monad: Monad m] [LawfulMonad m] (body : α → m β) :
    Vector.toList <$> (xs.mapM body) = xs.toList.mapM body := by
  rw [←Array.toList_mapM]
  suffices toList <$> mapM body xs = Array.toList <$> Array.mapM body xs.toArray by
    exact this
  rw [←Vector.toArray_mapM, Functor.map_map]
  congr

namespace Circuit
variable {prop : Condition F}

lemma ConstantLength.length_eq_default {circuit : α → Circuit F β} (_ : ConstantLength circuit) [Inhabited α] (a : α) (n : ℕ) :
   (circuit a).localLength n = (circuit default).localLength 0 := by
  simp only [ConstantLength.localLength_eq]

@[implicit_reducible] def ConstantLength.fromConstantLength' [Inhabited β] (body : β × Fin m → Circuit F β)
    (h : ∀ (acc : β) (i i' : Fin m) n,
      (body (acc, i)).localLength n = (body (default, i')).localLength 0) :
    ConstantLength body where
  localLength := match m with
    | 0 => 0
    | m + 1 => (body (default, 0)).localLength 0
  localLength_eq := by
    intro (b, i) n
    rcases m with rfl | m; nomatch i
    exact h b i 0 n

-- helper lemmas to characterize `forAll` statements on the operations generated by loops

lemma forAll_flatten_abstract (circuit : Fin m → Circuit F β) (constant : ConstantLength circuit) :
  Operations.forAll n prop (List.ofFn fun i => (circuit i).operations (n + i * constant.localLength)).flatten
    ↔ ∀ (i : Fin m), (circuit i).forAll (n + i * constant.localLength) prop := by
  induction m generalizing n
  case zero => simp [Operations.forAll]
  case succ m ih =>
    rw [List.ofFn_succ, List.flatten_cons, Operations.forAll_append, Fin.forall_fin_succ, Circuit.forAll_def]
    simp only [Fin.val_zero, zero_mul, add_zero, Fin.val_succ]
    let circuit' := fun i : Fin m => circuit i.succ
    let constant' : ConstantLength circuit' := {
      localLength := constant.localLength
      localLength_eq a n := constant.localLength_eq (a.succ) n }
    set k := constant.localLength
    specialize ih (n:=n + k) circuit' constant'
    set k' := constant'.localLength
    have : k' = k := rfl
    rw [this] at ih
    have : ((circuit 0).operations n).localLength + n = n + constant.localLength := by
      rw [←constant.localLength_eq 0 n]; ac_rfl
    rw [this]
    ring_nf at ih ⊢
    rw [ih]

lemma forAll_flatten (xs : Vector α m) {circuit : α → Circuit F β} (constant : ConstantLength circuit) :
  Operations.forAll n prop (List.ofFn fun (i : Fin m) => (circuit xs[i.val]).operations (n + i * constant.localLength)).flatten
    ↔ ∀ (i : Fin m), (circuit xs[i.val]).forAll (n + i * constant.localLength) prop :=
  forAll_flatten_abstract (fun i : Fin m => circuit xs[i.val]) {
    localLength := constant.localLength
    localLength_eq _ _ := constant.localLength_eq .. }

lemma forAllNoOffset_flatten_abstract {prop' : ConditionNoOffset F}
    (circuit : Fin m → Circuit F β) (constant : ConstantLength circuit) :
  Operations.forAllNoOffset prop' ((List.ofFn fun i => (circuit i).operations (n + i * constant.localLength)).flatten) ↔
    ∀ (i : Fin m),
      Operations.forAllNoOffset prop' ((circuit i).operations (n + i * constant.localLength)) := by
  induction m generalizing n with
  | zero => simp [Operations.forAllNoOffset]
  | succ m ih =>
    rw [List.ofFn_succ, List.flatten_cons, Operations.forAllNoOffset_append, Fin.forall_fin_succ]
    simp only [Fin.val_zero, zero_mul, add_zero, Fin.val_succ]
    let circuit' := fun i : Fin m => circuit i.succ
    let constant' : ConstantLength circuit' := {
      localLength := constant.localLength
      localLength_eq a n := constant.localLength_eq a.succ n }
    set k := constant.localLength
    specialize ih (n := n + k) circuit' constant'
    set k' := constant'.localLength
    have : k' = k := rfl
    rw [this] at ih
    ring_nf at ih ⊢
    rw [ih]

lemma forAllNoOffset_flatten {prop' : ConditionNoOffset F}
    (xs : Vector α m) {circuit : α → Circuit F β} (constant : ConstantLength circuit) :
  Operations.forAllNoOffset prop' ((List.ofFn fun (i : Fin m) => (circuit xs[i.val]).operations (n + i * constant.localLength)).flatten) ↔
    ∀ (i : Fin m),
      Operations.forAllNoOffset prop' ((circuit xs[i.val]).operations (n + i * constant.localLength)) :=
  forAllNoOffset_flatten_abstract (fun i : Fin m => circuit xs[i.val]) {
    localLength := constant.localLength
    localLength_eq _ _ := constant.localLength_eq .. }

-- helper lemma to do induction on (List.ofFn ...).flatten terms
private lemma ofFn_flatten_cons {circuit : α → Circuit F β} (constant : ConstantLength circuit) (x : α) (xs : Vector α m) (n : ℕ) :
  (List.ofFn fun (i : Fin (m + 1)) =>
      (circuit (Vector.listCons x xs)[i.val]).operations (n + i.val * constant.localLength)).flatten
    = (circuit x).operations n ++ (List.ofFn fun (i : Fin m) =>
      (circuit xs[i.val]).operations (n + constant.localLength + i.val * constant.localLength)).flatten := by
  simp +arith [Vector.listCons, Nat.succ_mul]

namespace ForM
variable {circuit : α → Circuit F Unit} (xs : Vector α m) (constant : ConstantLength circuit) (n : ℕ)

theorem localLength_eq : (xs.forM circuit).localLength n = m * constant.localLength := by
  set k := constant.localLength
  induction xs using Vector.induct generalizing n
  case nil => ac_rfl
  case cons x xs ih =>
    rw [Vector.forM_toList, Vector.listCons, Vector.toList_mk, List.forM_cons, ←Vector.forM_toList,
      bind_localLength_eq, ih, constant.localLength_eq]
    ring

theorem output_eq : (xs.forM circuit).output n = () := rfl

theorem operations_eq :
  (xs.forM circuit).operations n =
    (List.ofFn fun (i : Fin m) => (circuit xs[i.val]).operations (n + i * constant.localLength)).flatten := by
  induction xs using Vector.induct generalizing n
  case nil => rfl
  case cons x xs ih =>
    rw [ofFn_flatten_cons, Vector.forM_toList, Vector.listCons, Vector.toList_mk, List.forM_cons, ←Vector.forM_toList,
      bind_operations_eq, ih, constant.localLength_eq]

theorem forAll_iff {prop : Condition F} :
  (xs.forM circuit).forAll n prop ↔
    ∀ (i : Fin m), (circuit xs[i.val]).forAll (n + i * constant.localLength) prop := by
  rw [forAll_def, operations_eq, forAll_flatten]

theorem forAllNoOffset_iff {prop' : ConditionNoOffset F} :
  ((xs.forM circuit).operations n).forAllNoOffset prop' ↔
    ∀ (i : Fin m),
      ((circuit xs[i.val]).operations (n + i * constant.localLength)).forAllNoOffset prop' := by
  rw [operations_eq, forAllNoOffset_flatten]

end ForM

namespace MapM
variable {circuit : α → Circuit F β} {xs : Vector α m} [constant: ConstantLength circuit]
  {prop : Condition F} {prop' : ConditionNoOffset F}

theorem localLength_eq : (xs.mapM circuit).localLength n = m * constant.localLength := by
  induction xs using Vector.inductPush
  case nil =>
    rw [zero_mul]
    apply Eq.trans
    · apply congrArg (fun c : Circuit F (Vector β 0) => c.localLength n)
      exact Vector.mapM_mk_empty
    exact pure_localLength_eq #v[] n
  case push xs x ih =>
    rw [Vector.mapM_push, bind_localLength_eq, bind_localLength_eq, pure_localLength_eq, ih, constant.localLength_eq]
    ring

theorem output_eq : (xs.mapM circuit).output n =
    xs.mapIdx fun i x => (circuit x).output (n + i * constant.localLength) := by
  induction xs using Vector.inductPush
  case nil => simp
  case push xs x ih =>
    rw [Vector.mapM_push, bind_output_eq, bind_output_eq, pure_output_eq, ih, localLength_eq]
    simp

lemma ext_map_toList (f g : Circuit F (Vector α n)) :
    (fun v => v.toList) <$> f = (fun v => v.toList) <$> g → f = g := by
  intro h
  rw [ext_iff] at h
  ext1 n
  · replace h := (h n).left
    rw [map_output_eq, map_output_eq] at h
    exact Vector.toList_inj.mp h
  · replace h := (h n).right
    rw [map_operations_eq, map_operations_eq] at h
    exact h

lemma mapM_cons (xs : Vector α n) (body : α → Circuit F β) (x : α) :
  (Vector.listCons x xs).mapM body = do
    let y ← body x
    let ys ← xs.mapM body
    return Vector.listCons y ys := by
  apply ext_map_toList
  rw [Vector.toList_mapM, Vector.toList_listCons, List.mapM_cons, ←Vector.toList_mapM]
  simp only [map_bind, map_pure]
  rfl

theorem operations_eq : (xs.mapM circuit).operations n =
    (List.ofFn fun (i : Fin m) => (circuit xs[i.val]).operations (n + i * constant.localLength)).flatten := by
  induction xs using Vector.induct generalizing n
  case nil =>
    rw [List.ofFn_zero, List.flatten_nil]
    apply Eq.trans
    · apply congrArg (fun c : Circuit F (Vector β 0) => c.operations n)
      exact Vector.mapM_mk_empty
    exact pure_operations_eq #v[] n
  case cons x xs ih =>
    rw [mapM_cons, bind_operations_eq, bind_operations_eq, pure_operations_eq, ih,
      constant.localLength_eq, List.append_nil, ofFn_flatten_cons]

theorem forAll_iff :
  (xs.mapM circuit).forAll n prop ↔
    ∀ (i : Fin m), (circuit xs[i.val]).forAll (n + i * constant.localLength) prop := by
  rw [forAll_def, operations_eq, forAll_flatten]

theorem forAllNoOffset_iff :
  ((xs.mapM circuit).operations n).forAllNoOffset prop' ↔
    ∀ (i : Fin m), ((circuit xs[i.val]).operations (n + i * constant.localLength)).forAllNoOffset prop' := by
  rw [operations_eq, forAllNoOffset_flatten]

-- specialization to mapFinRangeM
theorem mapFinRangeM_forAll_iff {circuit : Fin m → Circuit F β} [constant : ConstantLength circuit] :
  (Vector.mapFinRangeM m circuit).forAll n prop ↔
    ∀ i : Fin m, (circuit i).forAll (n + i*constant.localLength) prop := by
  rw [Vector.mapFinRangeM, forAll_iff]
  simp only [Vector.getElem_finRange]

theorem mapFinRangeM_forAllNoOffset_iff {circuit : Fin m → Circuit F β}
    [constant : ConstantLength circuit] :
  ((Vector.mapFinRangeM m circuit).operations n).forAllNoOffset prop' ↔
    ∀ i : Fin m, ((circuit i).operations (n + i * constant.localLength)).forAllNoOffset prop' := by
  rw [Vector.mapFinRangeM, forAllNoOffset_iff]
  simp only [Vector.getElem_finRange]

end MapM

namespace FoldlM
@[reducible]
def prod (circuit : β → α → Circuit F β) : β × α → Circuit F β := fun t => circuit t.1 t.2

variable {env : ProverEnvironment F} {prop : Condition F} {prop' : ConditionNoOffset F} {xs : Vector α m}
  {circuit : β → α → Circuit F β} {init : β} {constant : ConstantLength (prod circuit)}

lemma foldlM_cons (x : α) :
  (Vector.listCons x xs).foldlM circuit init = (do
    let init' ← circuit init x
    xs.foldlM circuit init') := by
  rw [← Vector.foldlM_toList, Vector.listCons, Vector.toList_mk, List.foldlM_cons]
  simp only [Vector.foldlM_toList]

theorem localLength_eq :
    (xs.foldlM circuit init).localLength n = m * constant.localLength := by
  induction xs using Vector.induct generalizing init n
  case nil => rw [zero_mul]; rfl
  case cons x xs ih =>
    rw [foldlM_cons, bind_localLength_eq, ih, constant.localLength_eq (init, x)]
    ring

lemma finFoldl_cons_succ (x : α) :
  Fin.foldl (m + 1) (fun acc i => (circuit acc (Vector.listCons x xs)[i.val]).output (n + i * constant.localLength)) init
    = Fin.foldl m (fun acc i => (circuit acc xs[i.val]).output (n + constant.localLength + i * constant.localLength)) ((circuit init x).output n) := by
  set k := constant.localLength
  rw [Fin.foldl_succ]
  simp only [Fin.val_succ, Fin.val_zero, zero_mul, add_zero]
  congr
  funext acc i
  rw [add_mul, add_assoc, add_comm k]
  simp [Vector.listCons]

theorem output_eq :
  (xs.foldlM circuit init).output n =
    Fin.foldl m (fun acc i => (circuit acc xs[i.val]).output (n + i * constant.localLength)) init := by
  induction xs using Vector.induct generalizing init n
  case nil => aesop
  case cons x xs ih =>
    rw [foldlM_cons, bind_output_eq, ih, constant.localLength_eq (init, x), finFoldl_cons_succ]

def foldlAcc (n : ℕ) (xs : Vector α m) (circuit : β → α → Circuit F β) (init : β) (j : Fin m) : β :=
  Fin.foldl j (fun acc i => (circuit acc xs[i.val]).output (n + i*(circuit acc xs[i.val]).localLength)) init

lemma foldlAcc_zero [NeZero m] : foldlAcc n xs circuit init 0 = init := by
  simp [foldlAcc, Fin.foldl_zero]

lemma foldlAcc_cons_succ (i : Fin m) (x : α) [constant : ConstantLength (prod circuit)] :
  foldlAcc n (Vector.listCons x xs) circuit init i.succ =
    foldlAcc (n + (circuit init x).localLength n) xs circuit ((circuit init x).output n) i := by
  simp only [foldlAcc]
  simp only [Fin.val_succ, Vector.listCons, Vector.getElem_mk, List.getElem_toArray, Fin.foldl_succ,
    List.getElem_cons_succ, add_mul, one_mul,
    Fin.val_zero, List.getElem_cons_zero, zero_mul, add_zero]
  congr
  funext acc j
  rw [constant.localLength_eq (init, x), ←constant.localLength_eq (acc, _) 0]
  ac_rfl

theorem operations_eq :
  (Vector.foldlM circuit init xs).operations n =
    (List.ofFn fun i => (circuit (foldlAcc n xs circuit init i) xs[i.val]).operations (n + i * constant.localLength)).flatten := by
  induction xs using Vector.induct generalizing n init with
  | nil => rfl
  | cons x xs ih =>
    rw [foldlM_cons, bind_operations_eq, ih, List.ofFn_succ, List.flatten_cons]
    simp only [foldlAcc_cons_succ, foldlAcc_zero]
    simp +arith [Vector.listCons, add_mul, constant.localLength_eq (init, x)]

variable {prop : Condition F}

lemma forAll_flatten_foldl :
  Operations.forAll n prop (List.ofFn fun (i : Fin m) => (circuit (foldlAcc n xs circuit init i) xs[i.val]).operations (n + i * constant.localLength)).flatten
    ↔ ∀ (i : Fin m), (circuit (foldlAcc n xs circuit init i) xs[i.val]).forAll (n + i * constant.localLength) prop :=
  forAll_flatten_abstract (fun i : Fin m => circuit (foldlAcc n xs circuit init i) xs[i.val]) {
    localLength := constant.localLength
    localLength_eq i n := constant.localLength_eq (_, _) _
  }

lemma forAllNoOffset_flatten_foldl :
  Operations.forAllNoOffset prop' ((List.ofFn fun (i : Fin m) =>
        (circuit (foldlAcc n xs circuit init i) xs[i.val]).operations (n + i * constant.localLength)).flatten)
    ↔ ∀ (i : Fin m),
      Operations.forAllNoOffset prop' ((circuit (foldlAcc n xs circuit init i) xs[i.val]).operations (n + i * constant.localLength)) :=
  forAllNoOffset_flatten_abstract (fun i : Fin m => circuit (foldlAcc n xs circuit init i) xs[i.val]) {
    localLength := constant.localLength
    localLength_eq i n := constant.localLength_eq (_, _) _
  }

theorem forAll_iff {constant : ConstantLength (prod circuit)} :
  (xs.foldlM circuit init).forAll n prop ↔
    ∀ i : Fin m, (circuit (foldlAcc n xs circuit init i) xs[i.val]).forAll (n + i * (circuit init xs[i.val]).localLength) prop := by
  rw [forAll_def, operations_eq, forAll_flatten_foldl, iff_iff_eq]
  congr!
  rw [←constant.localLength_eq (init, _)]

theorem forAllNoOffset_iff {constant : ConstantLength (prod circuit)} :
  ((xs.foldlM circuit init).operations n).forAllNoOffset prop' ↔
    ∀ i : Fin m,
      ((circuit (foldlAcc n xs circuit init i) xs[i.val]).operations
        (n + i * (circuit init xs[i.val]).localLength)).forAllNoOffset prop' := by
  rw [operations_eq, forAllNoOffset_flatten_foldl, iff_iff_eq]
  congr!
  rw [←constant.localLength_eq (init, _)]

-- specialization to xs := Vector.finRange m
section
variable {env : ProverEnvironment F} {prop : Condition F} {m : ℕ}
  {Acc : ℕ → Type}
  {circuit : β → Fin m → Circuit F β} {init : β} {constant : ConstantLength (prod circuit)}

theorem forAll_iff_finRange {constant : ConstantLength (prod circuit)} :
  ((Vector.finRange m).foldlM circuit init).forAll n prop ↔
    ∀ i : Fin m, (circuit (foldlAcc n (Vector.finRange m) circuit init i) i)
    |>.forAll (n + i * (circuit init i).localLength) prop := by
  simp only [forAll_iff, Vector.getElem_finRange]

theorem forAllNoOffset_iff_finRange {constant : ConstantLength (prod circuit)} :
  (((Vector.finRange m).foldlM circuit init).operations n).forAllNoOffset prop' ↔
    ∀ i : Fin m,
      ((circuit (foldlAcc n (Vector.finRange m) circuit init i) i).operations
        (n + i * (circuit init i).localLength)).forAllNoOffset prop' := by
  simp only [forAllNoOffset_iff, Vector.getElem_finRange]

end
-- we can massively simplify the foldlM theory when assuming the body's output is independent of the input

variable [Inhabited β] [Inhabited α] {h_const_out : ConstantOutput fun (t : β × α) => circuit t.1 t.2}

theorem foldlAcc_const_succ (constant : ConstantLength (prod circuit))
  (h_const_out : ConstantOutput fun (t : β × α) => circuit t.1 t.2)
  (i : ℕ) (hi : i + 1 < m) :
  foldlAcc n xs circuit init ⟨ i + 1, hi ⟩ =
    (circuit default xs[i]).output (n + i * (circuit default default).localLength) := by
  simp only [foldlAcc]
  conv => lhs; lhs; intro acc i; rw [h_const_out (acc, _),
    ConstantLength.length_eq_default constant (acc, _)]
  rw [h_const_out (_, xs[i])]
  simp only [prod, Fin.foldl_const, Fin.val_last]
  rfl

theorem foldlAcc_const (constant : ConstantLength (prod circuit))
  (h_const_out : ConstantOutput fun (t : β × α) => circuit t.1 t.2)
  (i : ℕ) (hi : i < m) :
  foldlAcc n xs circuit init ⟨ i, hi ⟩ = match i with
    | 0 => init
    | i + 1 => (circuit default xs[i]).output (n + i * (circuit default default).localLength) := by
  rcases i with _ | i
  · simp [foldlAcc]
  · rw [foldlAcc_const_succ constant h_const_out]

theorem operations_eq_const [NeZero m] (constant : ConstantLength (prod circuit))
    (h_const_out : ConstantOutput (prod circuit)) :
  (Vector.foldlM circuit init xs).operations n =
  (circuit init (xs[0]'(NeZero.pos m))).operations n ++
  (List.ofFn fun (⟨i, _⟩ : Fin (m - 1)) =>
    let k := (circuit default default).localLength
    let acc := (circuit default xs[i]).output (n + i*k)
    (circuit acc xs[i + 1]).operations (n + (i + 1)*k)).flatten := by
  rw [operations_eq]
  simp only
  set k := (circuit default default).localLength
  set k' := constant.localLength
  have : k' = k := by simp only [k]; rw [constant.localLength_eq (_, _)]
  rw [this]
  rcases m with rfl | m
  · nomatch ‹NeZero 0›
  rw [List.ofFn_succ, List.flatten_cons]
  simp only [foldlAcc_zero, Fin.val_zero, zero_mul, add_zero, Fin.val_succ, add_mul, one_mul,
    add_tsub_cancel_right, Nat.add_one_sub_one, Fin.cast_eq_self, List.append_cancel_left_eq]
  congr
  funext i
  rcases i with ⟨ i, hi ⟩
  simp only [Fin.succ_mk]
  rw [foldlAcc_const_succ constant h_const_out]

theorem forAll_iff_const [NeZero m] (constant : ConstantLength (prod circuit))
    (h_const_out : ConstantOutput (prod circuit)) :
  (xs.foldlM circuit init).forAll n prop ↔
  (circuit init (xs[0]'(NeZero.pos m))).forAll n prop ∧
  ∀ (i : ℕ) (hi : i + 1 < m),
    let acc := (circuit default xs[i]).output (n + i*(circuit default default).localLength);
    (circuit acc xs[i + 1]).forAll (n + (i + 1)*(circuit default default).localLength) prop := by
  rw [forAll_iff (constant:=constant)]
  set k := (circuit default default).localLength
  simp only
  constructor
  · intro h
    constructor
    · specialize h 0
      simp only [Fin.val_zero] at h
      rw [foldlAcc_zero, zero_mul, add_zero] at h
      exact h
    · intro i hi
      specialize h ⟨ i + 1, hi ⟩
      rw [foldlAcc_const_succ constant h_const_out] at h
      convert h using 3
      rw [ConstantLength.length_eq_default constant (init, _)]
      rfl
  intro h i
  rcases i with ⟨ _ | i, hi ⟩
  · simp only [Fin.mk_zero']
    rw [foldlAcc_zero, zero_mul, add_zero]
    exact h.left
  · rw [foldlAcc_const_succ constant h_const_out]
    convert (h.right i hi) using 3
    rw [ConstantLength.length_eq_default constant (init, _)]
    rfl

theorem forAllNoOffset_iff_const [NeZero m] (constant : ConstantLength (prod circuit))
    (h_const_out : ConstantOutput (prod circuit)) :
  ((xs.foldlM circuit init).operations n).forAllNoOffset prop' ↔
  ((circuit init (xs[0]'(NeZero.pos m))).operations n).forAllNoOffset prop' ∧
  ∀ (i : ℕ) (hi : i + 1 < m),
    let acc := (circuit default xs[i]).output (n + i*(circuit default default).localLength);
    ((circuit acc xs[i + 1]).operations (n + (i + 1)*(circuit default default).localLength)).forAllNoOffset prop' := by
  rw [forAllNoOffset_iff (constant:=constant)]
  set k := (circuit default default).localLength
  simp only
  constructor
  · intro h
    constructor
    · specialize h 0
      simp only [Fin.val_zero] at h
      rw [foldlAcc_zero, zero_mul, add_zero] at h
      exact h
    · intro i hi
      specialize h ⟨ i + 1, hi ⟩
      rw [foldlAcc_const_succ constant h_const_out] at h
      convert h using 3
      rw [ConstantLength.length_eq_default constant (init, _)]
      rfl
  intro h i
  rcases i with ⟨ _ | i, hi ⟩
  · simp only [Fin.mk_zero']
    rw [foldlAcc_zero, zero_mul, add_zero]
    exact h.left
  · rw [foldlAcc_const_succ constant h_const_out]
    convert (h.right i hi) using 3
    rw [ConstantLength.length_eq_default constant (init, _)]
    rfl

end FoldlM

def forEach {m : ℕ} [Inhabited α] (xs : Vector α m) (body : α → Circuit F Unit)
    (_constant : ConstantLength body := by infer_constant_length) : Circuit F Unit :=
  xs.forM body

theorem forEach_cons {m : ℕ} [Inhabited α] (x : α) (xs : Vector α m) (body : α → Circuit F Unit)
    (constant : ConstantLength body) :
    forEach (Vector.listCons x xs) body constant = body x *> forEach xs body constant := by
  unfold forEach
  rw [Vector.forM_toList, Vector.listCons, Vector.toList_mk, List.forM_cons]
  rw [←Vector.forM_toList]
  rfl

def map {m : ℕ} (xs : Vector α m) (body : α → Circuit F β)
    (_constant : ConstantLength body := by infer_constant_length) : Circuit F (Vector β m) :=
  xs.mapM body

def mapFinRange (m : ℕ) [NeZero m] (body : Fin m → Circuit F β)
    (_constant : ConstantLength body := by infer_constant_length) : Circuit F (Vector β m) :=
  Vector.mapFinRangeM m body

def foldl {m : ℕ} [Inhabited β] [Inhabited α] (xs : Vector α m) (init : β) (body : β → α → Circuit F β)
  (_const_out : ConstantOutput (fun (s, a) => body s a) := by
    simp only [circuit_norm]
    intros
    rfl)
  (_constant : ConstantLength (fun (s, a) => body s a) := by infer_constant_length)
   : Circuit F β :=
  xs.foldlM body init

def foldlRange (m : ℕ) [Inhabited β] (init : β) (body : β → Fin m → Circuit F β)
  (_constant : ConstantLength (fun (s, a) => body s a) := by
    apply Circuit.ConstantLength.fromConstantLength'
    try simp only [circuit_norm]
    try intros
    try ac_rfl) : Circuit F β :=
  (Vector.finRange m).foldlM body init

section forEach
variable {env : ProverEnvironment F} {env_v : Environment F} {m n : ℕ} [Inhabited α] {xs : Vector α m}
  {body : α → Circuit F Unit} {constant : ConstantLength body} {prop : Condition F}
  {prop' : ConditionNoOffset F}

@[circuit_norm ↓]
lemma forEach.localLength_eq :
    (forEach xs body constant).localLength n = m * (body default).localLength := by
  rw [forEach, ForM.localLength_eq, constant.localLength_eq]

@[circuit_norm ↓]
lemma forEach.output_eq :
  (forEach xs body constant).output n = () := rfl

lemma forEach.operations_eq :
    (forEach xs body constant).operations n =
      (List.ofFn fun (i : Fin m) =>
        (body xs[i.val]).operations (n + i * (body default).localLength)).flatten := by
  simp only [forEach]
  rw [ForM.operations_eq, ConstantLength.localLength_eq]

@[circuit_norm ↓]
lemma forEach.subcircuitChannelsWithGuarantees :
  ((forEach xs body constant).operations n).subcircuitChannelsWithGuarantees =
    (List.ofFn fun (i : Fin m) =>
      (body xs[i.val]).operations (n + i * (body default).localLength) |>.subcircuitChannelsWithGuarantees).flatten := by
  rw [forEach.operations_eq]
  simp only [Operations.subcircuitChannelsWithGuarantees]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma forEach.subcircuitChannelsWithRequirements :
  ((forEach xs body constant).operations n).subcircuitChannelsWithRequirements =
    (List.ofFn fun (i : Fin m) =>
      (body xs[i.val]).operations (n + i * (body default).localLength) |>.subcircuitChannelsWithRequirements).flatten := by
  rw [forEach.operations_eq]
  simp only [Operations.subcircuitChannelsWithRequirements]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma forEach.shallowChannels :
  ((forEach xs body constant).operations n).shallowChannels =
    (List.ofFn fun (i : Fin m) =>
      (body xs[i.val]).operations (n + i * (body default).localLength) |>.shallowChannels).flatten := by
  rw [forEach.operations_eq]
  simp only [Operations.shallowChannels]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma forEach.forAll :
  Operations.forAll n prop ((forEach xs body constant).operations n) ↔
    ∀ i : Fin m, (body xs[i.val] |>.forAll (n + i*(body default).localLength) prop) := by
  simp only [forEach, ←forAll_def]
  rw [ForM.forAll_iff, ConstantLength.localLength_eq]

@[circuit_norm ↓]
lemma forEach.forAllNoOffset :
  ((forEach xs body constant).operations n).forAllNoOffset prop' ↔
    ∀ i : Fin m,
      ((body xs[i.val]).operations (n + i*(body default).localLength)).forAllNoOffset prop' := by
  simp only [forEach]
  rw [ForM.forAllNoOffset_iff, ConstantLength.localLength_eq]

@[circuit_norm ↓]
lemma forEach.usesLocalWitnesses :
  env.UsesLocalWitnessesCompleteness n ((forEach xs body constant).operations n) ↔
    ∀ i : Fin m, env.UsesLocalWitnessesCompleteness (n + i*(body default).localLength) (body xs[i.val] |>.operations (n + i*(body default).localLength)) := by
  simp only [forEach, env.usesLocalWitnessesCompleteness_iff_forAll, ←forAll_def]
  rw [ForM.forAll_iff, ConstantLength.localLength_eq]
end forEach

section map
variable {env : ProverEnvironment F} {env_v : Environment F} {m n : ℕ} [Inhabited α] {xs : Vector α m}
  {body : α → Circuit F β} {constant : ConstantLength body} {prop : Condition F}
  {prop' : ConditionNoOffset F}

@[circuit_norm ↓]
lemma map.localLength_eq :
    (map xs body constant).localLength n = m * (body default).localLength := by
  rw [map, MapM.localLength_eq, constant.localLength_eq]

@[circuit_norm ↓]
lemma map.output_eq :
  (map xs body constant).output n =
    xs.mapIdx fun i x => (body x).output (n + i*(body default).localLength) := by
  rw [map, MapM.output_eq, ConstantLength.localLength_eq]

lemma map.operations_eq :
    (map xs body constant).operations n =
      (List.ofFn fun (i : Fin m) =>
        (body xs[i.val]).operations (n + i * (body default).localLength)).flatten := by
  simp only [map]
  rw [MapM.operations_eq, ConstantLength.localLength_eq]

@[circuit_norm ↓]
lemma map.subcircuitChannelsWithGuarantees :
    ((map xs body constant).operations n).subcircuitChannelsWithGuarantees =
      (List.ofFn fun (i : Fin m) =>
        (body xs[i.val]).operations (n + i * (body default).localLength) |>.subcircuitChannelsWithGuarantees).flatten := by
  rw [map.operations_eq]
  simp only [Operations.subcircuitChannelsWithGuarantees]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma map.subcircuitChannelsWithRequirements :
    ((map xs body constant).operations n).subcircuitChannelsWithRequirements =
      (List.ofFn fun (i : Fin m) =>
        (body xs[i.val]).operations (n + i * (body default).localLength) |>.subcircuitChannelsWithRequirements).flatten := by
  rw [map.operations_eq]
  simp only [Operations.subcircuitChannelsWithRequirements]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma map.shallowChannels :
    ((map xs body constant).operations n).shallowChannels =
      (List.ofFn fun (i : Fin m) =>
        (body xs[i.val]).operations (n + i * (body default).localLength) |>.shallowChannels).flatten := by
  rw [map.operations_eq]
  simp only [Operations.shallowChannels]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma map.forAll :
  Operations.forAll n prop (map xs body constant |>.operations n) ↔
    ∀ i : Fin m, (body xs[i.val] |>.forAll (n + i*(body default).localLength) prop) := by
  simp only [map, ←forAll_def]
  rw [MapM.forAll_iff, ConstantLength.localLength_eq]

@[circuit_norm ↓]
lemma map.forAllNoOffset :
  ((map xs body constant).operations n).forAllNoOffset prop' ↔
    ∀ i : Fin m,
      ((body xs[i.val]).operations (n + i*(body default).localLength)).forAllNoOffset prop' := by
  simp only [map]
  rw [MapM.forAllNoOffset_iff, ConstantLength.localLength_eq]

@[circuit_norm ↓]
lemma map.usesLocalWitnesses :
  env.UsesLocalWitnessesCompleteness n (map xs body constant |>.operations n) ↔
    ∀ i : Fin m, env.UsesLocalWitnessesCompleteness (n + i*(body default).localLength) (body xs[i.val] |>.operations (n + i*(body default).localLength)) := by
  simp only [map, env.usesLocalWitnessesCompleteness_iff_forAll, ←forAll_def]
  rw [MapM.forAll_iff, ConstantLength.localLength_eq]
end map

section mapFinRange
variable {env : ProverEnvironment F} {env_v : Environment F} {m n : ℕ} [NeZero m] {body : Fin m → Circuit F β}
  {constant : ConstantLength body} {prop : Condition F} {prop' : ConditionNoOffset F}

@[circuit_norm ↓]
lemma mapFinRange.localLength_eq :
    (mapFinRange m body constant).localLength n = m * (body 0).localLength := by
  rw [mapFinRange, Vector.mapFinRangeM, MapM.localLength_eq, constant.localLength_eq]

@[circuit_norm ↓]
lemma mapFinRange.output_eq :
  (mapFinRange m body constant).output n =
    Vector.mapFinRange m fun i => (body i).output (n + i*(body 0).localLength) := by
  rw [mapFinRange, Vector.mapFinRangeM, MapM.output_eq, ConstantLength.localLength_eq]
  ext i hi
  rw [Vector.getElem_mapIdx, Vector.getElem_finRange, Vector.getElem_mapFinRange]

lemma mapFinRange.operations_eq : (mapFinRange m body constant).operations n =
    (List.ofFn fun (i : Fin m) => (body i).operations (n + i * (body 0).localLength)).flatten := by
  rw [mapFinRange, Vector.mapFinRangeM, MapM.operations_eq]
  simp only [Vector.getElem_finRange]
  congr! with i
  rw [constant.localLength_eq 0 0]

@[circuit_norm ↓]
lemma mapFinRange.subcircuitChannelsWithGuarantees :
  ((mapFinRange m body constant).operations n).subcircuitChannelsWithGuarantees =
    (List.ofFn fun (i : Fin m) =>
      (body i).operations (n + i * (body 0).localLength) |>.subcircuitChannelsWithGuarantees).flatten := by
  rw [mapFinRange.operations_eq]
  simp only [Operations.subcircuitChannelsWithGuarantees]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma mapFinRange.subcircuitChannelsWithRequirements :
  ((mapFinRange m body constant).operations n).subcircuitChannelsWithRequirements =
    (List.ofFn fun (i : Fin m) =>
      (body i).operations (n + i * (body 0).localLength) |>.subcircuitChannelsWithRequirements).flatten := by
  rw [mapFinRange.operations_eq]
  simp only [Operations.subcircuitChannelsWithRequirements]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma mapFinRange.shallowChannels :
  ((mapFinRange m body constant).operations n).shallowChannels =
    (List.ofFn fun (i : Fin m) =>
      (body i).operations (n + i * (body 0).localLength) |>.shallowChannels).flatten := by
  rw [mapFinRange.operations_eq]
  simp only [Operations.shallowChannels]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma mapFinRange.forAll :
  Operations.forAll n prop (mapFinRange m body constant |>.operations n) ↔
    ∀ i : Fin m, (body i |>.forAll (n + i*(body 0).localLength) prop) := by
  simp only [mapFinRange, ←forAll_def]
  rw [MapM.mapFinRangeM_forAll_iff, ConstantLength.localLength_eq]

@[circuit_norm ↓]
lemma mapFinRange.forAll' :
  ((mapFinRange m body constant).operations n).forAllNoOffset prop' ↔
    ∀ i : Fin m, ((body i).operations (n + i*(body 0).localLength)).forAllNoOffset prop' := by
  simp only [mapFinRange]
  rw [MapM.mapFinRangeM_forAllNoOffset_iff, ConstantLength.localLength_eq]

@[circuit_norm ↓]
lemma mapFinRange.usesLocalWitnesses :
  env.UsesLocalWitnessesCompleteness n (mapFinRange m body constant |>.operations n) ↔
    ∀ i : Fin m, env.UsesLocalWitnessesCompleteness (n + i*(body 0).localLength) (body i |>.operations (n + i*(body 0).localLength)) := by
  simp only [mapFinRange, env.usesLocalWitnessesCompleteness_iff_forAll, ←forAll_def]
  rw [MapM.mapFinRangeM_forAll_iff, ConstantLength.localLength_eq]
end mapFinRange

section foldl
variable {env : ProverEnvironment F} {env_v : Environment F} {m n : ℕ} [Inhabited β] [Inhabited α] {xs : Vector α m}
  {body : β → α → Circuit F β} {init : β} {constant : ConstantLength fun (t : β × α) => body t.1 t.2}
  {const_out : ConstantOutput (fun (t : β × α) => body t.1 t.2)}
  {prop' : ConditionNoOffset F}

@[circuit_norm ↓]
lemma foldl.localLength_eq :
    (foldl xs init body const_out constant).localLength n = m * (body default default).localLength := by
  rw [foldl, FoldlM.localLength_eq, constant.localLength_eq (_, _)]

@[circuit_norm ↓]
lemma foldl.output_eq [NeZero m] :
  (foldl xs init body const_out constant).output n =
    (body default (xs[m-1]'(Nat.pred_lt (NeZero.ne m)))).output (n + (m-1)*(body default default).localLength) := by
  rw [foldl, FoldlM.output_eq]
  unfold FoldlM.prod
  rw [constant.localLength_eq (default, default) 0]
  set k := constant.localLength
  have : m-1 < m := Nat.pred_lt (NeZero.ne m)
  rw [const_out (_, xs[m-1])]
  conv => lhs; lhs; intro acc i; rw [const_out (acc, _)]
  rcases m with _ | m
  · nomatch this
  simp only [Fin.foldl_const, Fin.val_last, add_tsub_cancel_right]

lemma foldl.operations_eq :
    (foldl xs init body const_out constant).operations n =
      (List.ofFn fun (i : Fin m) =>
        (body (FoldlM.foldlAcc n xs body init i) xs[i.val]).operations
          (n + i * (body default default).localLength)).flatten := by
  rw [foldl, FoldlM.operations_eq]
  congr! 4
  rw [constant.localLength_eq (_, _) _]

@[circuit_norm ↓]
lemma foldl.subcircuitChannelsWithGuarantees :
    ((foldl xs init body const_out constant).operations n).subcircuitChannelsWithGuarantees =
      (List.ofFn fun (i : Fin m) =>
        (body (FoldlM.foldlAcc n xs body init i) xs[i.val]).operations
          (n + i * (body default default).localLength) |>.subcircuitChannelsWithGuarantees).flatten := by
  rw [foldl.operations_eq]
  simp only [Operations.subcircuitChannelsWithGuarantees]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma foldl.subcircuitChannelsWithRequirements :
    ((foldl xs init body const_out constant).operations n).subcircuitChannelsWithRequirements =
      (List.ofFn fun (i : Fin m) =>
        (body (FoldlM.foldlAcc n xs body init i) xs[i.val]).operations
          (n + i * (body default default).localLength) |>.subcircuitChannelsWithRequirements).flatten := by
  rw [foldl.operations_eq]
  simp only [Operations.subcircuitChannelsWithRequirements]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma foldl.shallowChannels :
    ((foldl xs init body const_out constant).operations n).shallowChannels =
      (List.ofFn fun (i : Fin m) =>
        (body (FoldlM.foldlAcc n xs body init i) xs[i.val]).operations
          (n + i * (body default default).localLength) |>.shallowChannels).flatten := by
  rw [foldl.operations_eq]
  simp only [Operations.shallowChannels]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma foldl.forAll [NeZero m] :
  Operations.forAll n prop (foldl xs init body const_out constant |>.operations n) ↔
    (body init (xs[0]'(NeZero.pos m)) |>.forAll n prop) ∧
    ∀ (i : ℕ) (hi : i + 1 < m),
      let k := (body default default).localLength;
      let acc := (body default xs[i]).output (n + i*k);
      (body acc xs[i + 1]).forAll (n + (i + 1)*k) prop := by
  simp only [foldl, ←forAll_def]
  rw [FoldlM.forAll_iff_const constant const_out]

@[circuit_norm ↓]
lemma foldl.forAllNoOffset [NeZero m] :
  ((foldl xs init body const_out constant).operations n).forAllNoOffset prop' ↔
    ((body init (xs[0]'(NeZero.pos m))).operations n).forAllNoOffset prop' ∧
    ∀ (i : ℕ) (hi : i + 1 < m),
      let k := (body default default).localLength;
      let acc := (body default xs[i]).output (n + i*k);
      ((body acc xs[i + 1]).operations (n + (i + 1)*k)).forAllNoOffset prop' := by
  simp only [foldl]
  rw [FoldlM.forAllNoOffset_iff_const constant const_out]

@[circuit_norm ↓]
lemma foldl.usesLocalWitnesses [NeZero m] :
  env.UsesLocalWitnessesCompleteness n (foldl xs init body const_out constant |>.operations n) ↔
    env.UsesLocalWitnessesCompleteness n (body init (xs[0]'(NeZero.pos m)) |>.operations n) ∧
    ∀ (i : ℕ) (hi : i + 1 < m),
      let k := (body default default).localLength;
      let acc := (body default xs[i]).output (n + i*k);
      env.UsesLocalWitnessesCompleteness (n + (i + 1)*k) (body acc xs[i + 1] |>.operations (n + (i + 1)*k)) := by
  simp only [foldl, env.usesLocalWitnessesCompleteness_iff_forAll, ←forAll_def]
  rw [FoldlM.forAll_iff_const constant const_out]
end foldl

section foldlRange
variable {env : ProverEnvironment F} {env_v : Environment F} {m n : ℕ} [Inhabited β]
  {body : β → Fin m → Circuit F β} {init : β} {constant : ConstantLength fun (t : β × Fin m) => body t.1 t.2}
  {prop' : ConditionNoOffset F}

@[circuit_norm ↓]
lemma foldlRange.localLength_eq :
    (foldlRange m init body constant).localLength n =
      if h : m > 0 then m * (body default ⟨0, h⟩).localLength else 0 := by
  rw [foldlRange, FoldlM.localLength_eq (constant:=constant)]
  rcases m with rfl | m; simp
  have : m + 1 > 0 := by omega
  simp only [this, ↓reduceDIte]
  rw [constant.localLength_eq (_, _)]

@[circuit_norm ↓]
lemma foldlRange.output_eq :
  (foldlRange m init body constant).output n =
    Fin.foldl m (fun acc i => (body acc i).output (n + i*(body default i).localLength)) init := by
  rw [foldlRange, FoldlM.output_eq (constant:=constant)]
  simp only [Vector.getElem_finRange, Fin.eta]
  congr! 6
  rw [constant.localLength_eq (_, _)]

lemma foldlRange.operations_eq :
  (foldlRange m init body constant).operations n =
    (List.ofFn fun i =>
      (body (FoldlM.foldlAcc n (Vector.finRange m) body init i) i).operations
        (n + i * (body default i).localLength)).flatten := by
  rw [foldlRange, FoldlM.operations_eq]
  simp only [Vector.getElem_finRange]
  congr! 4
  rw [constant.localLength_eq (_, _)]

@[circuit_norm ↓]
lemma foldlRange.subcircuitChannelsWithGuarantees :
  ((foldlRange m init body constant).operations n).subcircuitChannelsWithGuarantees =
    (List.ofFn fun i =>
      (body (FoldlM.foldlAcc n (Vector.finRange m) body init i) i).operations
        (n + i * (body default i).localLength) |>.subcircuitChannelsWithGuarantees).flatten := by
  rw [foldlRange.operations_eq]
  simp only [Operations.subcircuitChannelsWithGuarantees]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma foldlRange.subcircuitChannelsWithRequirements :
  ((foldlRange m init body constant).operations n).subcircuitChannelsWithRequirements =
    (List.ofFn fun i =>
      (body (FoldlM.foldlAcc n (Vector.finRange m) body init i) i).operations
        (n + i * (body default i).localLength) |>.subcircuitChannelsWithRequirements).flatten := by
  rw [foldlRange.operations_eq]
  simp only [Operations.subcircuitChannelsWithRequirements]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma foldlRange.shallowChannels :
  ((foldlRange m init body constant).operations n).shallowChannels =
    (List.ofFn fun i =>
      (body (FoldlM.foldlAcc n (Vector.finRange m) body init i) i).operations
        (n + i * (body default i).localLength) |>.shallowChannels).flatten := by
  rw [foldlRange.operations_eq]
  simp only [Operations.shallowChannels]
  rw [List.map_flatten, List.flatten_flatten]
  apply congrArg List.flatten
  rw [List.map_ofFn, List.map_ofFn]
  rfl

@[circuit_norm ↓]
lemma foldlRange.forAll :
  Operations.forAll n prop (foldlRange m init body constant |>.operations n) ↔
    ∀ i : Fin m,
      body (FoldlM.foldlAcc n (Vector.finRange m) body init i) i
      |>.forAll (n + i * (body default i).localLength) prop := by
  simp only [foldlRange, ←forAll_def]
  rw [FoldlM.forAll_iff_finRange (constant:=constant)]
  congr! 4
  rw [constant.localLength_eq (_, _), constant.localLength_eq (_, _)]

@[circuit_norm ↓]
lemma foldlRange.forAllNoOffset :
  ((foldlRange m init body constant).operations n).forAllNoOffset prop' ↔
    ∀ i : Fin m,
      ((body (FoldlM.foldlAcc n (Vector.finRange m) body init i) i).operations
        (n + i * (body default i).localLength)).forAllNoOffset prop' := by
  simp only [foldlRange]
  rw [FoldlM.forAllNoOffset_iff_finRange (constant:=constant)]
  congr! 4
  rw [constant.localLength_eq (_, _), constant.localLength_eq (_, _)]

@[circuit_norm ↓]
lemma foldlRange.usesLocalWitnesses :
  env.UsesLocalWitnessesCompleteness n (foldlRange m init body constant |>.operations n) ↔
    ∀ i : Fin m,
      env.UsesLocalWitnessesCompleteness (n + i * (body default i).localLength) (body (FoldlM.foldlAcc n (Vector.finRange m) body init i) i
      |>.operations (n + i * (body default i).localLength)) := by
  simp only [env.usesLocalWitnessesCompleteness_iff_forAll, foldlRange.forAll]
end foldlRange
end Circuit

theorem Operations.channelsLawful_flatten_of_forall {m : ℕ}
    {ops : Fin m → Operations F}
    {channelsWithGuarantees : Fin m → List (RawChannel F)} :
    (∀ i, (ops i).ChannelsLawful (channelsWithGuarantees i)) →
    Operations.ChannelsLawful (List.ofFn ops).flatten
      (List.ofFn channelsWithGuarantees).flatten := by
  intro h
  induction m with
  | zero => simp [Operations.channelsLawful_nil]
  | succ m ih =>
    rw [List.ofFn_succ, List.ofFn_succ]
    rw [List.flatten_cons, List.flatten_cons]
    apply Operations.channelsLawful_append_of_channelsLawful
    · exact h 0
    · apply ih
      intro i
      exact h i.succ

namespace ExplicitCircuit
open Circuit (ConstantLength ConstantOutput forEach map mapFinRange foldl foldlRange)

@[explicit_circuit_constructor, implicit_reducible, explicit_circuit_norm]
def from_forEach {m : ℕ} [Inhabited α] {xs : Vector α m}
    {body : α → Circuit F Unit} (explicit : ∀ a, ExplicitCircuit (body a))
    {constant : ConstantLength body} : ExplicitCircuit (forEach xs body constant) where
  output _ := ()
  localLength _ := m * (explicit default).localLength 0
  operations n := (List.ofFn fun (i : Fin m) =>
    (explicit xs[i.val]).operations (n + i * ((explicit default).localLength 0))).flatten
  channelsWithGuarantees n := (List.ofFn fun (i : Fin m) =>
    (explicit xs[i.val]).channelsWithGuarantees (n + i * ((explicit default).localLength 0))).flatten
  output_eq n := Circuit.forEach.output_eq
  localLength_eq n := by
    rw [forEach.localLength_eq, localLength_eq]
  operations_eq n := by
    simp only [forEach.operations_eq, localLength_eq, operations_eq]
  subcircuitsConsistent n := by
    rw [forEach.operations_eq, Operations.SubcircuitsConsistent]
    rw [show (List.ofFn fun i : Fin m => (body xs[i.val]).operations (n + ↑i * (body default).localLength)).flatten =
        (List.ofFn fun i : Fin m => (body xs[i.val]).operations (n + ↑i * constant.localLength)).flatten by
      congr! 4
      rw [←constant.localLength_eq default 0]]
    rw [Circuit.forAll_flatten xs (circuit:=body) constant]
    intro i
    apply (explicit _).subcircuitsConsistent
  channelsLawful n := by
    rw [forEach.operations_eq, localLength_eq]
    apply Operations.channelsLawful_flatten_of_forall
    intro i
    apply (explicit _).channelsLawful

@[circuit_norm, explicit_circuit_norm]
theorem from_forEach_output {m : ℕ} [Inhabited α] {xs : Vector α m}
    {body : α → Circuit F Unit} [explicit : ∀ a, ExplicitCircuit (body a)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_forEach explicit (xs:=xs) (constant:=constant)).output n = () := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_forEach_localLength {m : ℕ} [Inhabited α] {xs : Vector α m}
    {body : α → Circuit F Unit} [explicit : ∀ a, ExplicitCircuit (body a)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_forEach explicit (xs:=xs) (constant:=constant)).localLength n =
      m * (explicit default).localLength 0 := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_forEach_operations {m : ℕ} [Inhabited α] {xs : Vector α m}
    {body : α → Circuit F Unit} [explicit : ∀ a, ExplicitCircuit (body a)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_forEach explicit (xs:=xs) (constant:=constant)).operations n =
      (List.ofFn fun (i : Fin m) => (explicit xs[i.val]).operations (n + i * ((explicit default).localLength 0))).flatten := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_forEach_channelsWithGuarantees {m : ℕ} [Inhabited α] {xs : Vector α m}
    {body : α → Circuit F Unit} [explicit : ∀ a, ExplicitCircuit (body a)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_forEach explicit (xs:=xs) (constant:=constant)).channelsWithGuarantees n =
      (List.ofFn fun (i : Fin m) => (explicit xs[i.val]).channelsWithGuarantees (n + i * ((explicit default).localLength 0))).flatten := rfl

@[explicit_circuit_constructor, implicit_reducible, explicit_circuit_norm]
def from_map_loop {m : ℕ} [Inhabited α] {xs : Vector α m}
    {body : α → Circuit F β} (explicit : ∀ a, ExplicitCircuit (body a))
    {constant : ConstantLength body} : ExplicitCircuit (map xs body constant) where
  output n := xs.mapIdx fun i x => (explicit x).output (n + i * ((explicit default).localLength 0))
  localLength _ := m * (explicit default).localLength 0
  operations n := (List.ofFn fun (i : Fin m) =>
    (explicit xs[i.val]).operations (n + i * ((explicit default).localLength 0))).flatten
  channelsWithGuarantees n := (List.ofFn fun (i : Fin m) =>
    (explicit xs[i.val]).channelsWithGuarantees (n + i * ((explicit default).localLength 0))).flatten
  output_eq n := by
    simp only [map.output_eq, localLength_eq, output_eq]
  localLength_eq n := by
    rw [map.localLength_eq, localLength_eq]
  operations_eq n := by
    simp only [map.operations_eq, localLength_eq, operations_eq]
  subcircuitsConsistent n := by
    rw [map.operations_eq, Operations.SubcircuitsConsistent]
    rw [show (List.ofFn fun i : Fin m => (body xs[i.val]).operations (n + ↑i * (body default).localLength)).flatten =
        (List.ofFn fun i : Fin m => (body xs[i.val]).operations (n + ↑i * constant.localLength)).flatten by
      congr! 4
      rw [←constant.localLength_eq default 0]]
    rw [Circuit.forAll_flatten xs (circuit:=body) constant]
    intro i
    apply (explicit _).subcircuitsConsistent
  channelsLawful n := by
    rw [map.operations_eq, localLength_eq]
    apply Operations.channelsLawful_flatten_of_forall
    intro i
    apply (explicit _).channelsLawful

@[circuit_norm, explicit_circuit_norm]
theorem from_map_loop_output {m : ℕ} [Inhabited α] {xs : Vector α m}
    {body : α → Circuit F β} [explicit : ∀ a, ExplicitCircuit (body a)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_map_loop explicit (xs:=xs) (constant:=constant)).output n =
      xs.mapIdx fun i x => (explicit x).output (n + i * ((explicit default).localLength 0)) := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_map_loop_localLength {m : ℕ} [Inhabited α] {xs : Vector α m}
    {body : α → Circuit F β} [explicit : ∀ a, ExplicitCircuit (body a)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_map_loop explicit (xs:=xs) (constant:=constant)).localLength n =
      m * (explicit default).localLength 0 := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_map_loop_operations {m : ℕ} [Inhabited α] {xs : Vector α m}
    {body : α → Circuit F β} [explicit : ∀ a, ExplicitCircuit (body a)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_map_loop explicit (xs:=xs) (constant:=constant)).operations n =
      (List.ofFn fun (i : Fin m) => (explicit xs[i.val]).operations (n + i * ((explicit default).localLength 0))).flatten := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_map_loop_channelsWithGuarantees {m : ℕ} [Inhabited α] {xs : Vector α m}
    {body : α → Circuit F β} [explicit : ∀ a, ExplicitCircuit (body a)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_map_loop explicit (xs:=xs) (constant:=constant)).channelsWithGuarantees n =
      (List.ofFn fun (i : Fin m) => (explicit xs[i.val]).channelsWithGuarantees (n + i * ((explicit default).localLength 0))).flatten := rfl

@[explicit_circuit_constructor, implicit_reducible, explicit_circuit_norm]
def from_mapFinRange {m : ℕ} [NeZero m]
    {body : Fin m → Circuit F β} (explicit : ∀ i, ExplicitCircuit (body i))
    {constant : ConstantLength body} : ExplicitCircuit (mapFinRange m body constant) where
  output n := Vector.mapFinRange m fun i => (explicit i).output (n + i * ((explicit 0).localLength 0))
  localLength _ := m * (explicit 0).localLength 0
  operations n := (List.ofFn fun (i : Fin m) =>
    (explicit i).operations (n + i * ((explicit 0).localLength 0))).flatten
  channelsWithGuarantees n := (List.ofFn fun (i : Fin m) =>
    (explicit i).channelsWithGuarantees (n + i * ((explicit 0).localLength 0))).flatten
  output_eq n := by
    simp only [mapFinRange.output_eq, localLength_eq, output_eq]
  localLength_eq n := by
    rw [mapFinRange.localLength_eq, localLength_eq]
  operations_eq n := by
    simp only [mapFinRange.operations_eq, localLength_eq, operations_eq]
  subcircuitsConsistent n := by
    rw [mapFinRange.operations_eq, Operations.SubcircuitsConsistent]
    rw [show (List.ofFn fun i : Fin m => (body i).operations (n + ↑i * (body 0).localLength)).flatten =
        (List.ofFn fun i : Fin m => (body i).operations (n + ↑i * constant.localLength)).flatten by
      congr! with i
      rw [constant.localLength_eq 0 0]]
    rw [Circuit.forAll_flatten_abstract (circuit:=body) constant]
    intro i
    apply (explicit _).subcircuitsConsistent
  channelsLawful n := by
    rw [mapFinRange.operations_eq, localLength_eq]
    apply Operations.channelsLawful_flatten_of_forall
    intro i
    apply (explicit _).channelsLawful

attribute [explicit_circuit_no_unfold] Circuit.forEach Circuit.map Circuit.mapFinRange Circuit.foldl Circuit.foldlRange

@[circuit_norm, explicit_circuit_norm]
theorem from_mapFinRange_output {m : ℕ} [NeZero m]
    {body : Fin m → Circuit F β} [explicit : ∀ i, ExplicitCircuit (body i)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_mapFinRange explicit (constant:=constant)).output n =
      Vector.mapFinRange m fun i => (explicit i).output (n + i * ((explicit 0).localLength 0)) := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_mapFinRange_localLength {m : ℕ} [NeZero m]
    {body : Fin m → Circuit F β} [explicit : ∀ i, ExplicitCircuit (body i)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_mapFinRange explicit (constant:=constant)).localLength n =
      m * (explicit 0).localLength 0 := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_mapFinRange_operations {m : ℕ} [NeZero m]
    {body : Fin m → Circuit F β} [explicit : ∀ i, ExplicitCircuit (body i)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_mapFinRange explicit (constant:=constant)).operations n =
      (List.ofFn fun (i : Fin m) => (explicit i).operations (n + i * ((explicit 0).localLength 0))).flatten := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_mapFinRange_channelsWithGuarantees {m : ℕ} [NeZero m]
    {body : Fin m → Circuit F β} [explicit : ∀ i, ExplicitCircuit (body i)]
    {constant : ConstantLength body} (n : ℕ) :
    (from_mapFinRange explicit (constant:=constant)).channelsWithGuarantees n =
      (List.ofFn fun (i : Fin m) => (explicit i).channelsWithGuarantees (n + i * ((explicit 0).localLength 0))).flatten := rfl

@[explicit_circuit_constructor, implicit_reducible, explicit_circuit_norm]
def from_foldl {m : ℕ} [Inhabited α] [Inhabited β] {xs : Vector α m}
    -- `explicit` is a regular explicit binder (not `[explicit]`) so the `infer_explicit_head`
    -- dispatch leaves it as a subgoal for the enclosing `infer_explicit_circuit` loop to solve
    -- (`intro b a; infer_explicit_head`), rather than going through typeclass synthesis — which
    -- is unpredictable on loop bodies (resolves for KeccakRound, fails for FullRound) and on
    -- failure collapses the apply into a deep `from_bind` chain. Matches the Vector loops above.
    {body : β → α → Circuit F β} (explicit : ∀ b a, ExplicitCircuit (body b a)) {init : β}
    {constant : ConstantLength fun (t : β × α) => body t.1 t.2}
    {const_out : ConstantOutput (fun (t : β × α) => body t.1 t.2)} :
    ExplicitCircuit (foldl xs init body const_out constant) where
  output n := if h : m > 0 then
    (explicit default (xs[m-1]'(Nat.pred_lt (Nat.ne_of_gt h)))).output
      (n + (m-1)*((explicit default default).localLength 0))
    else init
  localLength _ := m * (explicit default default).localLength 0
  operations n := (List.ofFn fun (i : Fin m) =>
    (explicit (Circuit.FoldlM.foldlAcc n xs body init i) xs[i.val]).operations
      (n + i * ((explicit default default).localLength 0))).flatten
  channelsWithGuarantees n := (List.ofFn fun (i : Fin m) =>
    (explicit (Circuit.FoldlM.foldlAcc n xs body init i) xs[i.val]).channelsWithGuarantees
      (n + i * ((explicit default default).localLength 0))).flatten
  output_eq n := by
    by_cases h : m > 0
    · have : NeZero m := NeZero.of_pos h
      simp only [h, ↓reduceDIte]
      rw [foldl.output_eq]
      rw [(explicit default (xs[m-1])).output_eq]
      congr 1
      rw [(explicit default default).localLength_eq]
    · have hm : m = 0 := Nat.eq_zero_of_not_pos h
      subst m
      simp only [h, ↓reduceDIte]
      rw [foldl]
      cases xs with
      | mk toArray hsize =>
        simp at hsize ⊢
        cases toArray
        simp_all
        rfl
  localLength_eq n := by
    rw [foldl.localLength_eq]
    rw [(explicit default default).localLength_eq]
  operations_eq n := by
    rw [foldl.operations_eq]
    congr with i
    rw [(explicit (Circuit.FoldlM.foldlAcc n xs body init i) xs[i.val]).operations_eq]
    rw [(explicit default default).localLength_eq]
  subcircuitsConsistent n := by
    rw [foldl.operations_eq, Operations.SubcircuitsConsistent]
    rw [show (List.ofFn fun i : Fin m =>
        (body (Circuit.FoldlM.foldlAcc n xs body init i) xs[i.val]).operations
          (n + ↑i * (body default default).localLength)).flatten =
        (List.ofFn fun i : Fin m =>
        (body (Circuit.FoldlM.foldlAcc n xs body init i) xs[i.val]).operations
          (n + ↑i * constant.localLength)).flatten by
      congr! with i
      rw [constant.localLength_eq (default, default) 0]]
    rw [Circuit.FoldlM.forAll_flatten_foldl (circuit:=body) (constant:=constant)]
    intro i
    exact (explicit (Circuit.FoldlM.foldlAcc n xs body init i) xs[i.val]).subcircuitsConsistent (n + i * constant.localLength)
  channelsLawful n := by
    rw [foldl.operations_eq]
    apply Operations.channelsLawful_flatten_of_forall
    intro i
    convert (explicit (Circuit.FoldlM.foldlAcc n xs body init i) xs[i.val]).channelsLawful
      (n + i * ((explicit default default).localLength 0)) using 1
    · rw [(explicit default default).localLength_eq]

@[explicit_circuit_constructor, implicit_reducible, explicit_circuit_norm]
def from_foldlRange {m : ℕ} [Inhabited β]
    {body : β → Fin m → Circuit F β} (explicit : ∀ b i, ExplicitCircuit (body b i)) {init : β}
    {constant : ConstantLength fun (t : β × Fin m) => body t.1 t.2} :
    ExplicitCircuit (foldlRange m init body constant) where
  output n := Fin.foldl m (fun acc i => (explicit acc i).output (n + i*((explicit default i).localLength 0))) init
  localLength _ := if h : m > 0 then m * (explicit default ⟨0, h⟩).localLength 0 else 0
  operations n := (List.ofFn fun i =>
    (explicit (Circuit.FoldlM.foldlAcc n (Vector.finRange m) body init i) i).operations
      (n + i * ((explicit default i).localLength 0))).flatten
  channelsWithGuarantees n := (List.ofFn fun i =>
    (explicit (Circuit.FoldlM.foldlAcc n (Vector.finRange m) body init i) i).channelsWithGuarantees
      (n + i * ((explicit default i).localLength 0))).flatten
  output_eq n := by
    rw [foldlRange.output_eq]
    congr with acc i
    rw [(explicit acc i).output_eq]
    congr 1
    rw [(explicit default i).localLength_eq]
  localLength_eq n := by
    rw [foldlRange.localLength_eq]
    by_cases h : m > 0
    · simp only [h, ↓reduceDIte]
      rw [(explicit default ⟨0, h⟩).localLength_eq]
    · simp only [h, ↓reduceDIte]
  operations_eq n := by
    rw [foldlRange.operations_eq]
    congr with i
    rw [(explicit (Circuit.FoldlM.foldlAcc n (Vector.finRange m) body init i) i).operations_eq]
    rw [(explicit default i).localLength_eq]
  subcircuitsConsistent n := by
    rw [Operations.SubcircuitsConsistent]
    change (foldlRange m init body constant).forAll n { subcircuit := fun offset {n} x => n = offset }
    rw [Circuit.forAll_def, foldlRange.forAll]
    intro i
    exact (explicit (Circuit.FoldlM.foldlAcc n (Vector.finRange m) body init i) i).subcircuitsConsistent
      (n + i * (body default i).localLength)
  channelsLawful n := by
    rw [foldlRange.operations_eq]
    apply Operations.channelsLawful_flatten_of_forall
    intro i
    convert (explicit (Circuit.FoldlM.foldlAcc n (Vector.finRange m) body init i) i).channelsLawful
      (n + i * ((explicit default i).localLength 0)) using 1
    · rw [(explicit default i).localLength_eq]

-- Lean 4.33 can leave these dependent structure projections stuck when the
-- proof arguments in the circuit and its explicit instance are propositionally,
-- but not syntactically, identical. Unfolding only the metadata constructors
-- lets projection reduction proceed without exposing the loop circuit body.
attribute [explicit_circuit_norm] from_foldl from_foldlRange

@[circuit_norm, explicit_circuit_norm]
theorem from_foldl_output {m : ℕ} [Inhabited α] [Inhabited β] {xs : Vector α m}
    {body : β → α → Circuit F β} [explicit : ∀ b a, ExplicitCircuit (body b a)] {init : β}
    {constant : ConstantLength fun (t : β × α) => body t.1 t.2}
    {const_out : ConstantOutput (fun (t : β × α) => body t.1 t.2)} (n : ℕ) :
    (from_foldl (xs:=xs) explicit (init:=init) (constant:=constant) (const_out:=const_out)).output n =
      (if h : m > 0 then
        (explicit default (xs[m-1]'(Nat.pred_lt (Nat.ne_of_gt h)))).output
          (n + (m-1)*((explicit default default).localLength 0))
        else init) := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_foldl_localLength {m : ℕ} [Inhabited α] [Inhabited β] {xs : Vector α m}
    {body : β → α → Circuit F β} [explicit : ∀ b a, ExplicitCircuit (body b a)] {init : β}
    {constant : ConstantLength fun (t : β × α) => body t.1 t.2}
    {const_out : ConstantOutput (fun (t : β × α) => body t.1 t.2)} (n : ℕ) :
    (from_foldl (xs:=xs) explicit (init:=init) (constant:=constant) (const_out:=const_out)).localLength n =
      m * (explicit default default).localLength 0 := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_foldl_operations {m : ℕ} [Inhabited α] [Inhabited β] {xs : Vector α m}
    {body : β → α → Circuit F β} [explicit : ∀ b a, ExplicitCircuit (body b a)] {init : β}
    {constant : ConstantLength fun (t : β × α) => body t.1 t.2}
    {const_out : ConstantOutput (fun (t : β × α) => body t.1 t.2)} (n : ℕ) :
    (from_foldl (xs:=xs) explicit (init:=init) (constant:=constant) (const_out:=const_out)).operations n =
      (List.ofFn fun (i : Fin m) =>
        (explicit (Circuit.FoldlM.foldlAcc n xs body init i) xs[i.val]).operations
          (n + i * ((explicit default default).localLength 0))).flatten := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_foldlRange_output {m : ℕ} [Inhabited β]
    {body : β → Fin m → Circuit F β} [explicit : ∀ b i, ExplicitCircuit (body b i)] {init : β}
    {constant : ConstantLength fun (t : β × Fin m) => body t.1 t.2} (n : ℕ) :
    (from_foldlRange explicit (init:=init) (constant:=constant)).output n =
      Fin.foldl m (fun acc i => (explicit acc i).output (n + i*((explicit default i).localLength 0))) init := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_foldlRange_localLength {m : ℕ} [Inhabited β]
    {body : β → Fin m → Circuit F β} [explicit : ∀ b i, ExplicitCircuit (body b i)] {init : β}
    {constant : ConstantLength fun (t : β × Fin m) => body t.1 t.2} (n : ℕ) :
    (from_foldlRange explicit (init:=init) (constant:=constant)).localLength n =
      if h : m > 0 then m * (explicit default ⟨0, h⟩).localLength 0 else 0 := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_foldlRange_operations {m : ℕ} [Inhabited β]
    {body : β → Fin m → Circuit F β} [explicit : ∀ b i, ExplicitCircuit (body b i)] {init : β}
    {constant : ConstantLength fun (t : β × Fin m) => body t.1 t.2} (n : ℕ) :
    (from_foldlRange explicit (init:=init) (constant:=constant)).operations n =
      (List.ofFn fun i =>
        (explicit (Circuit.FoldlM.foldlAcc n (Vector.finRange m) body init i) i).operations
      (n + i * ((explicit default i).localLength 0))).flatten := rfl

@[circuit_norm, explicit_circuit_norm]
theorem from_foldlRange_channelsWithGuarantees {m : ℕ} [Inhabited β]
    {body : β → Fin m → Circuit F β} (explicit : ∀ b i, ExplicitCircuit (body b i)) {init : β}
    {constant : ConstantLength fun (t : β × Fin m) => body t.1 t.2} (n : ℕ) :
    (from_foldlRange explicit (init:=init) (constant:=constant)).channelsWithGuarantees n =
      (List.ofFn fun i =>
        (explicit (Circuit.FoldlM.foldlAcc n (Vector.finRange m) body init i) i).channelsWithGuarantees
          (n + i * ((explicit default i).localLength 0))).flatten := rfl

end ExplicitCircuit

namespace Circuit
-- a few theorems about loops + interactions
-- TODO for circuit simplification we will need `interactionsWith` versions

private theorem interactions_flatten_eq_map (ops : List (Operations F)) :
    Operations.interactions ops.flatten = (ops.map Operations.interactions).flatten := by
  induction ops with
  | nil => rfl
  | cons op ops ih =>
    simp [Operations.interactions_append, ih]

/-- Interactions of `map` are the concatenation of the interactions of its body circuits. -/
@[circuit_norm ↓]
theorem interactions_map {m : ℕ} (xs : Vector α m) (body : α → Circuit F β)
    (constant : ConstantLength body) (offset : ℕ) :
    ((map xs body constant).operations offset).interactions =
      (List.ofFn fun (i : Fin m) =>
        ((body xs[i]).operations (offset + i * constant.localLength)).interactions).flatten := by
  rw [map, MapM.operations_eq, interactions_flatten_eq_map, List.map_ofFn]
  rfl

@[circuit_norm ↓]
theorem interactions_forEach {m : ℕ} [Inhabited α] (xs : Vector α m) (body : α → Circuit F Unit)
    (constant : ConstantLength body) (offset : ℕ) :
    ((forEach xs body constant).operations offset).interactions =
      (List.ofFn fun (i : Fin m) =>
        ((body xs[i]).operations (offset + i * constant.localLength)).interactions).flatten := by
  rw [forEach, ForM.operations_eq, interactions_flatten_eq_map, List.map_ofFn]
  rfl

@[circuit_norm ↓]
theorem channels_forEach {m : ℕ} [Inhabited α] (xs : Vector α m) (body : α → Circuit F Unit)
    (constant : ConstantLength body) (offset : ℕ) :
    ((forEach xs body constant).operations offset).channels =
      (List.ofFn fun (i : Fin m) =>
        ((body xs[i]).operations (offset + i * constant.localLength)).channels).flatten := by
  rw [Operations.channels, interactions_forEach, List.map_flatten]
  rw [List.map_ofFn]
  rfl

@[circuit_norm ↓]
theorem interactions_mapFinRange (m : ℕ) [NeZero m] (body : Fin m → Circuit F β)
    (constant : ConstantLength body) (offset : ℕ) :
    ((mapFinRange m body constant).operations offset).interactions =
      (List.ofFn fun (i : Fin m) =>
        ((body i).operations (offset + i * constant.localLength)).interactions).flatten := by
  rw [mapFinRange, Vector.mapFinRangeM, MapM.operations_eq, interactions_flatten_eq_map, List.map_ofFn]
  congr
  funext i
  simp [Vector.getElem_finRange]
end Circuit
